#! /bin/bash

cd ./src/
gcc -c ./stream.c     -I ../inc  -g
gcc -c ./str_opt.c    -I ../inc  -g
gcc -c ./runHist.c    -I ../inc  -g
gcc -c ./realArray.c  -I ../inc  -g
gcc -c ./Text.c       -I ../inc  -g
#gcc -c ./file_i.c  -I ../inc  -g
gcc -c ./file_o.c  -I ../inc  -g

cd ../

ar crv file_io.a src/stream.o src/str_opt.o src/runHist.o src/realArray.o src/Text.o src/file_o.o
ranlib file_io.a

gcc -c ./test.c -I ./inc -g
gcc -o test test.o file_io.a -lm
gcc -c ./test2.c -I ./inc -g
gcc -o test2 test2.o file_io.a -lm
gcc -c ./test3.c -I ./inc -g
gcc -o test3 test3.o file_io.a -lm
gcc -c ./test4.c -I ./inc -g
gcc -o test4 test4.o file_io.a -lm

exit 0
